spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      corsConfigurations:
        '[/**]':
          allowedOrigins: "*"
          allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          allowedHeaders:
            - "*"
          allowCredentials: true
      routes:
        - id: r1
          uri: lb://Product-Service
          predicates:
            - Path=/api/products/**, *
        - id: r2
          uri: lb://Sales-Order-Service
          predicates:
            - Path=/sales/**
        - id: r3
          uri: lb://Purchase-Order-Service
          predicates:
            - Path=/purchases/**
        - id: r4
          uri: lb://SupplierClient-Service
          predicates:
            - Path=/SupplierClients/**
        - id: r5
          uri: lb://Filter-Service
          predicates:
            - Path=/api/Filters/**
        - id: r6
          uri: lb://Security-Service
          predicates:
            - Path=/users/**
  server:
    tomcat:
      relaxed-query-chars: "|{}[]"